### ISSUE TITLE
セキュリティアップデートを整理する

### ISSUE THREAD

**Issue by rantan** [chaintope/tapyrus-explorer#130]
PR がたくさん作られているので整理して適用する。

**Comment by Yamaguchi** [comment]
現状マージできていないPRに関して
- Mochaのサポートがnode v14.0.0以降となっているためCIが失敗している
  - https://github.com/chaintope/tapyrus-explorer/pull/136
  - https://github.com/chaintope/tapyrus-explorer/pull/135
- angular (15.0.4)のサポートがnode v14.20.0以降となっているためCIが失敗している
  - https://github.com/chaintope/tapyrus-explorer/pull/124
  - https://github.com/chaintope/tapyrus-explorer/pull/116

**Comment by Yamaguchi** [comment]
tapryus-explorer の Node v10, v12サポートを切って、v14, v16, v18, v20にしたい

**Comment by Yamaguchi** [comment]
Nodeの最新は20.3.1

https://nodejs.org/ja/download/releases

Angularがサポートするバージョンは14.0.x以降だが、これに対応するNodeのバージョンは14.15.0以降

https://angular.jp/guide/versions

**Comment by Yamaguchi** [comment]
https://github.com/chaintope/tapyrus-explorer/pull/137

**Comment by Yamaguchi** [comment]
すべてのセキュリティアップデートを実施後、v0.1.0のタグをうってます。

https://github.com/chaintope/tapyrus-explorer/releases/tag/v0.1.0
