### ISSUE TITLE
Add time format notation for timestamp

### ISSUE THREAD

**Issue by azuchi** [chaintope/tapyrus-explorer#146]
Add time format notation for timestamp that are displayed numerically on block and transaction pages.

**Comment by rantan** [comment]
* Received Time の右に`(Jul 31, 2023 15:52:00 UTC)`  みたいに日付を入れる
* Verified Time の右に`(Jul 31, 2023 15:52:00 UTC)`  みたいに日付を入れる
* Tx 表示パネルの右に `Verifed: Jul 31 ...)` とある部分を `Confirmed: Jul 31, 2023 15:52:00 UTC` のようにする。

![Image](https://github.com/chaintope/tapyrus-explorer/assets/134133/837facf9-add6-45db-af0c-5fd5dd0587ee)


* Timestamp の右に`(Jul 31, 2023 15:52:00 UTC)`  みたいに日付を入れる
* 
![Image](https://github.com/chaintope/tapyrus-explorer/assets/134133/fabe8523-a952-45a3-8da3-28c8a99bb4f4)
