### ISSUE TITLE
Txns page does not show size

### ISSUE THREAD

**Issue by azuchi** [chaintope/tapyrus-explorer#155]
On the txns page, there is a size column in the header, but the size is not displayed in the data section.
<img width="1715" alt="スクリーンショット 2023-09-04 21 18 11" src="https://github.com/chaintope/tapyrus-explorer/assets/1539047/eb468486-f614-460a-925d-14631d7925c1">

**Comment by rantan** [comment]
size の追加が難しければ size の項目を消してもいい。
