### ISSUE TITLE
スクリプトを入力、出力の項目と一緒に表示する

### ISSUE THREAD

**Issue by rantan** [chaintope/tapyrus-explorer#159]
トランザクションの詳細画面で、inputs, outputs と input scripts, output scripts が別々に表示されているが、そのため各入力、出力とスクリプトの対応を見付けにくい。

現状の画面
![スクリーンショット 2023-09-29 134140](https://github.com/chaintope/tapyrus-explorer/assets/134133/5bad05a7-ddc2-4db9-b277-8f7ae182f121)

これを解決するために、inputs, outputs の各項目の中にスクリプトも入れ込んで表示する方が良い。

検討事項として、スクリプトを表示すると、スクリプトに関心がなくTPC か colored coin の金額とアドレスだけに関心があるユーザーからすると冗長になる。ボタンを配置し、スクリプト部分は開閉できるとなおよいと思う。

**Comment by Yamaguchi** [comment]
![Tapyrus-Explorer (3)](https://github.com/chaintope/tapyrus-explorer/assets/220267/f14c4e7e-43cd-4b09-9edc-dbb78c667a33)
![Tapyrus-Explorer (4)](https://github.com/chaintope/tapyrus-explorer/assets/220267/ef54fdbd-5dbf-4fa2-b389-fa99257b9316)
