### ISSUE TITLE
font color problem on macOS "Light Mode"

### ISSUE THREAD

**Issue by Yamaguchi** [chaintope/tapyrus-explorer#21]
Switching "Light Mode" on macOS cause changing the font color.
Then I can not recognize strings because font color seems to be the same as the background.

Dark Mode. It seems nice to me.
![スクリーンショット 2020-08-26 20 32 09（2）](https://user-images.githubusercontent.com/220267/91299501-a842e880-e7dc-11ea-9497-3434b3430fc2.png)

Light Mode. font color and background color are almost the same.
![スクリーンショット 2020-08-26 20 32 13（2）](https://user-images.githubusercontent.com/220267/91299520-b3961400-e7dc-11ea-994e-670e432339b1.png)

**Comment by Yamaguchi** [comment]
I check with two browsers.(left: Safari, right: Chrome)

**Comment by azuchi** [comment]
This problem has already been fixed.

**Comment by Yamaguchi** [comment]
I made sure it is fixed.
