### ISSUE TITLE
Colored coin support

### ISSUE THREAD

**Issue by Yamaguchi** [chaintope/tapyrus-explorer#55]
- Remove bitcoin-core dependency
    - https://github.com/chaintope/tapyrus-explorer/issues/62
- Show uncolored address in tranaction page or address page.
- Create new index in rocksDB to store coin information.
- Implement new Esplora REST API to get coins
- Create coins page to show all coins issued.

**Comment by rantan** [comment]
* 左メニューに Color ID 用の項目を追加する。選択するとColor ID の一覧を表示する。
* Color ID を選択すると以下のURLの画面が開く
     * https://explorer.api.tapyrus.chaintope.com/color/c214026e7cccef06780b174d1c8aa6e85f2c723ccd5b78aa780ebabf2b1caa9e17
